// =============================================================================
// USF FABRIC MONITORING - NUMBERED DAX MEASURES
// =============================================================================
// Version: 0.3.8+
// Author: Sanmi Ibitoye
// Last Updated: 2026-01-15
//
// PURPOSE
// - This file is a numbered variant of the canonical measures file.
// - It aligns with a Power BI model where measures are prefixed with numbers
//   (e.g., "1 Total Activities", "2 Failed Activities", ...).
//
// IMPORTANT
// - Counting MUST use SUM(fact_activity[record_count]) NOT COUNT(activity_id)
//   because most audit-log activities have NULL activity_id.
// - This file does NOT modify or replace the original measures file.
//
// =============================================================================


// =============================================================================
// SECTION 1: CORE KPI MEASURES (1-8)
// =============================================================================

1 Total Activities =
SUM(fact_activity[record_count])


2 Failed Activities =
CALCULATE(
    SUM(fact_activity[record_count]),
    fact_activity[is_failed] = 1
)


3 Successful Activities =
CALCULATE(
    SUM(fact_activity[record_count]),
    fact_activity[is_failed] = 0
)


4 Success Rate =
VAR TotalAct = [1 Total Activities]
VAR FailedAct = [2 Failed Activities]
RETURN
IF(
    TotalAct > 0,
    DIVIDE(TotalAct - FailedAct, TotalAct) * 100,
    BLANK()
)


5 Failure Rate =
IF(
    [1 Total Activities] > 0,
    DIVIDE([2 Failed Activities], [1 Total Activities]) * 100,
    BLANK()
)


6 Active Users =
DISTINCTCOUNT(fact_activity[user_sk])


7 Active Workspaces =
DISTINCTCOUNT(fact_activity[workspace_sk])


8 Active Items =
DISTINCTCOUNT(fact_activity[item_sk])


// =============================================================================
// SECTION 2: DURATION MEASURES (9-15)
// =============================================================================

9 Total Duration Hours =
DIVIDE(
    SUM(fact_activity[duration_seconds]),
    3600,
    0
)


10 Total Duration Minutes =
DIVIDE(
    SUM(fact_activity[duration_seconds]),
    60,
    0
)


11 Avg Duration Minutes =
DIVIDE(
    AVERAGE(fact_activity[duration_seconds]),
    60,
    0
)


12 Avg Duration Seconds =
AVERAGE(fact_activity[duration_seconds])


13 Max Duration Hours =
DIVIDE(
    MAX(fact_activity[duration_seconds]),
    3600,
    0
)


14 Long Running Activities =
CALCULATE(
    SUM(fact_activity[record_count]),
    fact_activity[is_long_running] = 1
)


15 Long Running Rate =
IF(
    [1 Total Activities] > 0,
    DIVIDE([14 Long Running Activities], [1 Total Activities]) * 100,
    BLANK()
)


// =============================================================================
// SECTION 3: TIME COMPARISON MEASURES (16-22)
// Notes:
// - These measures are “as-of” style KPIs.
// - AsOfDate anchors to the latest selected date, but never beyond TODAY().
// =============================================================================

16 Activities Today =
VAR AsOfDate = MIN(TODAY(), MAX(dim_date[full_date]))
RETURN
IF(
    ISBLANK(AsOfDate),
    BLANK(),
    CALCULATE(
        [1 Total Activities],
        REMOVEFILTERS(dim_date),
        dim_date[full_date] = AsOfDate
    )
)


17 Activities Yesterday =
VAR AsOfDate = MIN(TODAY(), MAX(dim_date[full_date]))
VAR Yesterday = AsOfDate - 1
RETURN
IF(
    ISBLANK(AsOfDate),
    BLANK(),
    CALCULATE(
        [1 Total Activities],
        REMOVEFILTERS(dim_date),
        dim_date[full_date] = Yesterday
    )
)


18 Activities Last 7 Days =
VAR AsOfDate = MIN(TODAY(), MAX(dim_date[full_date]))
RETURN
IF(
    ISBLANK(AsOfDate),
    BLANK(),
    CALCULATE(
        [1 Total Activities],
        REMOVEFILTERS(dim_date),
        DATESINPERIOD(dim_date[full_date], AsOfDate, -7, DAY)
    )
)


19 Activities Last 28 Days =
VAR AsOfDate = MIN(TODAY(), MAX(dim_date[full_date]))
RETURN
IF(
    ISBLANK(AsOfDate),
    BLANK(),
    CALCULATE(
        [1 Total Activities],
        REMOVEFILTERS(dim_date),
        DATESINPERIOD(dim_date[full_date], AsOfDate, -28, DAY)
    )
)


20 Activities Previous 7 Days =
VAR AsOfDate = MIN(TODAY(), MAX(dim_date[full_date]))
VAR PreviousWindowEnd = AsOfDate - 7
RETURN
IF(
    ISBLANK(AsOfDate),
    BLANK(),
    CALCULATE(
        [1 Total Activities],
        REMOVEFILTERS(dim_date),
        DATESINPERIOD(dim_date[full_date], PreviousWindowEnd, -7, DAY)
    )
)


21 DoD Change % =
VAR TodayAct = [16 Activities Today]
VAR YesterdayAct = [17 Activities Yesterday]
RETURN
IF(
    YesterdayAct > 0,
    DIVIDE(TodayAct - YesterdayAct, YesterdayAct) * 100,
    BLANK()
)


22 WoW Change % =
VAR ThisWeek = [18 Activities Last 7 Days]
VAR LastWeek = [20 Activities Previous 7 Days]
RETURN
IF(
    LastWeek > 0,
    DIVIDE(ThisWeek - LastWeek, LastWeek) * 100,
    BLANK()
)


// =============================================================================
// SECTION 4: TIME INTELLIGENCE (23-26)
// Recommended: mark dim_date as a Date table on dim_date[full_date]
// =============================================================================

23 Activities MTD =
VAR AsOfDate = MIN(TODAY(), MAX(dim_date[full_date]))
VAR MonthStart = DATE(YEAR(AsOfDate), MONTH(AsOfDate), 1)
RETURN
IF(
    ISBLANK(AsOfDate),
    BLANK(),
    CALCULATE(
        [1 Total Activities],
        DATESBETWEEN(dim_date[full_date], MonthStart, AsOfDate)
    )
)


24 Activities Previous Month =
VAR AsOfDate = MIN(TODAY(), MAX(dim_date[full_date]))
VAR PrevMonthStart = EOMONTH(AsOfDate, -2) + 1
VAR PrevMonthEnd = EOMONTH(AsOfDate, -1)
RETURN
IF(
    ISBLANK(AsOfDate),
    BLANK(),
    CALCULATE(
        [1 Total Activities],
        DATESBETWEEN(dim_date[full_date], PrevMonthStart, PrevMonthEnd)
    )
)


25 Activities YTD =
VAR AsOfDate = MIN(TODAY(), MAX(dim_date[full_date]))
VAR YearStart = DATE(YEAR(AsOfDate), 1, 1)
RETURN
IF(
    ISBLANK(AsOfDate),
    BLANK(),
    CALCULATE(
        [1 Total Activities],
        DATESBETWEEN(dim_date[full_date], YearStart, AsOfDate)
    )
)


26 MoM Change % =
VAR AsOfDate = MIN(TODAY(), MAX(dim_date[full_date]))
RETURN
IF(
    ISBLANK(AsOfDate),
    BLANK(),
    VAR CurrentMonthMTD = [23 Activities MTD]
    VAR PrevMonthStart = EOMONTH(AsOfDate, -2) + 1
    VAR PrevMonthEndCandidate = PrevMonthStart + DAY(AsOfDate) - 1
    VAR PrevMonthEnd = MIN(PrevMonthEndCandidate, EOMONTH(AsOfDate, -1))
    VAR PreviousMonthMTD =
        CALCULATE(
            [1 Total Activities],
            DATESBETWEEN(dim_date[full_date], PrevMonthStart, PrevMonthEnd)
        )
    RETURN
    IF(
        PreviousMonthMTD > 0,
        DIVIDE(CurrentMonthMTD - PreviousMonthMTD, PreviousMonthMTD) * 100,
        BLANK()
    )
)


// =============================================================================
// SECTION 5: ENVIRONMENT BREAKDOWN (27-32)
// =============================================================================

27 Production Activities =
CALCULATE(
    [1 Total Activities],
    dim_workspace[environment] = "PRD"
)


28 UAT Activities =
CALCULATE(
    [1 Total Activities],
    dim_workspace[environment] = "UAT"
)


29 Test Activities =
CALCULATE(
    [1 Total Activities],
    dim_workspace[environment] = "TEST"
)


30 Development Activities =
CALCULATE(
    [1 Total Activities],
    dim_workspace[environment] = "DEV"
)


31 Production Failure Rate =
CALCULATE(
    [5 Failure Rate],
    dim_workspace[environment] = "PRD"
)


32 Non-Production Activities =
CALCULATE(
    [1 Total Activities],
    dim_workspace[environment] <> "PRD"
)


// =============================================================================
// SECTION 6: ACTIVITY TYPE BREAKDOWN (33-38)
// =============================================================================

33 Pipeline Activities =
CALCULATE(
    [1 Total Activities],
    dim_activity_type[activity_category] = "Pipeline"
)


34 Notebook Activities =
CALCULATE(
    [1 Total Activities],
    dim_activity_type[activity_category] = "Notebook"
)


35 Dataflow Activities =
CALCULATE(
    [1 Total Activities],
    dim_activity_type[activity_category] = "Dataflow"
)


36 Lakehouse Activities =
CALCULATE(
    [1 Total Activities],
    dim_activity_type[activity_category] = "Lakehouse"
)


37 Semantic Model Activities =
CALCULATE(
    [1 Total Activities],
    dim_activity_type[activity_category] = "SemanticModel"
)


38 Report Activities =
CALCULATE(
    [1 Total Activities],
    dim_activity_type[activity_category] = "Report"
)


// =============================================================================
// SECTION 7: USER ANALYSIS (39-41)
// =============================================================================

39 Activities per User =
DIVIDE(
    [1 Total Activities],
    [6 Active Users],
    0
)


40 Top User Activities =
VAR CurrentUser = SELECTEDVALUE(dim_user[user_principal_name])
RETURN
CALCULATE(
    [1 Total Activities],
    dim_user[user_principal_name] = CurrentUser
)


41 User Rank =
RANKX(
    ALL(dim_user[user_principal_name]),
    [1 Total Activities],
    ,
    DESC,
    Dense
)


// =============================================================================
// SECTION 8: WORKSPACE ANALYSIS (42-44)
// =============================================================================

42 Activities per Workspace =
DIVIDE(
    [1 Total Activities],
    [7 Active Workspaces],
    0
)


43 Workspace Rank =
RANKX(
    ALL(dim_workspace[workspace_name]),
    [1 Total Activities],
    ,
    DESC,
    Dense
)


44 Workspace Success Rate =
VAR WsTotal = [1 Total Activities]
VAR WsFailed = [2 Failed Activities]
RETURN
IF(
    WsTotal > 0,
    DIVIDE(WsTotal - WsFailed, WsTotal) * 100,
    BLANK()
)


// =============================================================================
// SECTION 9: HOURLY ANALYSIS (45-47)
// =============================================================================

45 Business Hours Activities =
CALCULATE(
    [1 Total Activities],
    dim_time[is_business_hours] = TRUE()
)


46 Off-Hours Activities =
CALCULATE(
    [1 Total Activities],
    dim_time[is_business_hours] = FALSE()
)


47 Peak Hour =
VAR HourlyTable =
    ADDCOLUMNS(
        SUMMARIZE(fact_activity, dim_time[hour_24]),
        "HourCount", [1 Total Activities]
    )
VAR MaxCount = MAXX(HourlyTable, [HourCount])
RETURN
MAXX(
    FILTER(HourlyTable, [HourCount] = MaxCount),
    dim_time[hour_24]
)


// =============================================================================
// SECTION 10: CONDITIONAL FORMATTING (48-51)
// =============================================================================

48 Success Rate Color =
VAR Rate = [4 Success Rate]
RETURN
SWITCH(
    TRUE(),
    Rate >= 99, "#107C10",  // Green
    Rate >= 95, "#FFB900",  // Yellow
    "#E81123"               // Red
)


49 Failure Count Color =
VAR FailCount = [2 Failed Activities]
RETURN
SWITCH(
    TRUE(),
    FailCount = 0, "#107C10",   // Green
    FailCount <= 10, "#FFB900", // Yellow
    "#E81123"                   // Red
)


50 Trend Indicator =
VAR Change = [21 DoD Change %]
RETURN
SWITCH(
    TRUE(),
    Change > 0, "▲",
    Change < 0, "▼",
    "―"
)


51 Trend Color =
VAR Change = [21 DoD Change %]
RETURN
IF(Change >= 0, "#107C10", "#E81123")


// =============================================================================
// SECTION 11: SPARKLINE HELPER (52)
// =============================================================================

52 Daily Activity Trend =
CALCULATE(
    [1 Total Activities],
    ALLEXCEPT(dim_date, dim_date[full_date])
)


// =============================================================================
// SECTION 12: OPTIONAL “OPS” MEASURES (53+)
// These help build a more “actionable” monitoring dashboard.
// =============================================================================

53 Impacted Workspaces (Failures) =
CALCULATE(
    DISTINCTCOUNT(fact_activity[workspace_sk]),
    fact_activity[is_failed] = 1
)


54 Failure Days (Distinct) =
CALCULATE(
    DISTINCTCOUNT(dim_date[full_date]),
    fact_activity[is_failed] = 1
)


55 Failure Density (Failures/Day) =
DIVIDE(
    [2 Failed Activities],
    [54 Failure Days (Distinct)],
    0
)


56 Failed Duration Hours =
CALCULATE(
    [9 Total Duration Hours],
    fact_activity[is_failed] = 1
)


57 Failed Avg Duration Minutes =
CALCULATE(
    [11 Avg Duration Minutes],
    fact_activity[is_failed] = 1
)


58 P95 Duration Minutes =
DIVIDE(
    PERCENTILEX.INC(
        fact_activity,
        fact_activity[duration_seconds],
        0.95
    ),
    60,
    0
)


59 Scheduled Activities (Proxy) =
// Proxy for "scheduled tasks": focuses on common job-history-backed categories.
// Adjust the category list if your dim_activity_type differs.
CALCULATE(
    [1 Total Activities],
    dim_activity_type[activity_category] IN {"Pipeline", "Notebook", "Dataflow"}
)


60 Scheduled Failed Activities (Proxy) =
CALCULATE(
    [2 Failed Activities],
    dim_activity_type[activity_category] IN {"Pipeline", "Notebook", "Dataflow"}
)


61 Scheduled Failure Rate (Proxy) =
IF(
    [59 Scheduled Activities (Proxy)] > 0,
    DIVIDE([60 Scheduled Failed Activities (Proxy)], [59 Scheduled Activities (Proxy)]) * 100,
    BLANK()
)
